### ISSUE TITLE
ETH support

### ISSUE THREAD

**Issue by heleon19** [me-no-dev/AsyncTCP#10]
Can the lib be used with ETH on the ESP32 instead of WiFi?

**Comment by copercini** [comment]
yes, I'm using with ethernet

**Comment by ahk97** [comment]
Could you post any sample code, please?
I am using Wifi and ETH / W5500 and the AsyncTCP Webserver will only bind to the wifi interface
thanks

**Comment by me-no-dev** [comment]
not W5500 :) use a real ethernet PHY :) W5500 works through Arduino and does not attach to the LwIP stack. It will never work with Async.

**Comment by ahk97** [comment]
Which PHY would you recommend?
And, if I replace the W5500 with the recommended PHY, will WiFi and ETH work simultaneously with AsyncTCP? (I would like to start one AsyncWebServer and serve requests via either Interface).
Thanks!

**Comment by atanisoft** [comment]
@ahk97 any that are supported by esp-idf. The example readme for Ethernet phy with IDF has a few types that are supported: https://github.com/espressif/esp-idf/blob/master/examples/ethernet/basic/README.md
