### ISSUE TITLE
A lot of compiler-error-messages like error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}

### ISSUE THREAD

**Issue by StefanL38** [me-no-dev/AsyncTCP#113]
Hello,

I tried to compile a ESP32-webserver example from random nerd tutorials
but it spits out a huge amount of compiler-error-messages. See attached textfile

some examples
`C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:27: error: field call has incomplete type tcpip_api_call

     struct tcpip_api_call call;

                           ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: forward declaration of struct tcpip_api_call

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_output(tcp_pcb*):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:291:65: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_output_api, (struct tcpip_api_call*)&msg);

                                                                 ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:291:65: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_write(tcp_pcb*, const char*, size_t, uint8_t):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:307:64: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_write_api, (struct tcpip_api_call*)&msg);

                                                                ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:307:64: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_recved(tcp_pcb*, size_t):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:322:65: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_recved_api, (struct tcpip_api_call*)&msg);

                                                                 ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:322:65: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_connect(tcp_pcb*, ip_addr_t*, uint16_t, tcp_connected_fn):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:338:66: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_connect_api, (struct tcpip_api_call*)&msg);

                                                                  ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:338:66: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_close(tcp_pcb*):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:352:64: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_close_api, (struct tcpip_api_call*)&msg);

                                                                ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:352:64: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_abort(tcp_pcb*):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:367:64: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_abort_api, (struct tcpip_api_call*)&msg);

                                                                ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:367:64: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function esp_err_t _tcp_bind(tcp_pcb*, ip_addr_t*, uint16_t):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:382:63: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_bind_api, (struct tcpip_api_call*)&msg);

                                                               ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:382:63: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: In function tcp_pcb* _tcp_listen_with_backlog(tcp_pcb*, uint8_t):

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:397:65: error: invalid conversion from err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)} to tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)} [-fpermissive]

     tcpip_api_call(_tcp_listen_api, (struct tcpip_api_call*)&msg);

                                                                 ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:397:65: error: cannot convert tcpip_api_call* to tcpip_api_call_data* for argument 2 to err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: class type tcpip_api_call is incomplete

     struct tcpip_api_call call;

            ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp: At global scope:

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:624:6: error: prototype for void AsyncClient::_dns_found(ip_addr_t*) does not match any in class AsyncClient

 void AsyncClient::_dns_found(ip_addr_t *ipaddr){

      ^

In file included from C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:24:0:

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.h:84:10: error: candidate is: void AsyncClient::_dns_found(_ip_addr*)

     void _dns_found(struct _ip_addr *ipaddr);

          ^

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:946:6: error: prototype for void AsyncClient::_s_dns_found(const char*, ip_addr_t*, void*) does not match any in class AsyncClient

 void AsyncClient::_s_dns_found(const char * name, ip_addr_t * ipaddr, void * arg){

      ^

In file included from C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp:24:0:

C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP\src\AsyncTCP.h:164:17: error: candidate is: static void AsyncClient::_s_dns_found(const char*, _ip_addr*, void*)

     static void _s_dns_found(const char *name, struct _ip_addr *ipaddr, void *arg);

                 ^

Multiple include guards may be useful for:

C:\Users\Stefan\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/sdk/include/freertos/freertos/list.h

C:\Users\Stefan\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/sdk/include/lwip/arch/vfs_lwip.h

C:\Users\Stefan\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/sdk/include/newlib/sys/string.h

c:\users\stefan\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\lib\gcc\xtensa-esp32-elf\5.2.0\include-fixed\limits.h

c:\users\stefan\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\xtensa-esp32-elf\include\c++\5.2.0\cctype

c:\users\stefan\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\xtensa-esp32-elf\include\c++\5.2.0\clocale

Using library WiFi at version 1.0 in folder: C:\Users\Stefan\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi 
Using library ESPAsyncWebServer at version 1.2.0 in folder: C:\Users\Stefan\Documents\Arduino\libraries\ESPAsyncWebServer 
Using library FS at version 1.0 in folder: C:\Users\Stefan\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\FS 
Using library AsyncTCP at version 1.0.0 in folder: C:\Users\Stefan\Documents\Arduino\libraries\AsyncTCP 
exit status 1
Error compiling for board ESP32 Dev Module.`

How can I fix this?

**Comment by bertmelis** [comment]
If you'd looked carefully at the error message you could find that you are using an old version of this lib.
