### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by dwienie** [me-no-dev/AsyncTCP#132]
I have a loop where I do every 10 seconds a request. I have many times a sequence of : 
[E][AsyncTCP.cpp:934] _poll(): 0x3ffd2a4c != 0x2e323931   (these addresses can of course differ from case to case)
After some [E][AsyncTCP.cpp:934] _poll() I have a Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited)
So why I have these poll errors and why it generates a Guru Meditation error. 
There is something wrong with the error handling that makes the ESP32 crash.

Code Snippet that matters for this issue:
```
#include <Arduino.h>
#include <WiFi.h>
#include <AsyncHTTPRequest_Generic.h>
void requestCB(void* optParm, AsyncHTTPRequest* request, int readyState);
void ConnectToWifi();
void sendRequest(void);
unsigned long doRequest=0;
WiFiClient client;
AsyncHTTPRequest request;
void setup() {
  // put your setup code here, to run once:
    ConnectToWifi();
    request.onReadyStateChange(requestCB );
     
}

void loop(){
 if (millis()>doRequest + 10000)
    {
      sendRequest();
      doRequest = millis();
    };

void sendRequest(){
  
  if(request.readyState() == reqStates::readyStateUnsent || request.readyState() == reqStates::readyStateDone){
     
        if (request.open("GET", "http://192.168.1.183/api/v/1/status"))
        {
          
        if (request.send()==false)
          {
            request.abort();
            Serial.println("failed to send");
          }
          else
           Serial.println("send request");
        }
        else
        {
          Serial.println("failed to open");
          request.abort();
        };
       
    }
    else
  {
    Serial.print("not correct readystate in Status:");
    Serial.println(request.readyState());
    request.abort();
    
  }
void requestCB(void* optParm, AsyncHTTPRequest* request, int readyState)
{
Serial.println(readyState);
    if(readyState == reqStates::readyStateDone){
       if (request->responseHTTPcode()==200)
       {
         ;
         Serial.println(request->responseText());
   }                  
       else
       {
         Serial.print("httpcode:");
         Serial.println(request->responseHTTPcode());
        
       }
    }
}
```

**Comment by larryl79** [comment]
> I have a loop where I do every 10 seconds a request. I have many times a sequence of : [E][AsyncTCP.cpp:934] _poll(): 0x3ffd2a4c != 0x2e323931 (these addresses can of course differ from case to case) After some [E][AsyncTCP.cpp:934] _poll() I have a Guru Meditation Error: Core 1 panic'ed (InstrFetchProhibited) So why I have these poll errors and why it generates a Guru Meditation error. There is something wrong with the error handling that makes the ESP32 crash.
> 
> Code Snippet that matters for this issue:
> 
> ```
> #include <Arduino.h>
> #include <WiFi.h>
> #include <AsyncHTTPRequest_Generic.h>
> void requestCB(void* optParm, AsyncHTTPRequest* request, int readyState);
> void ConnectToWifi();
> void sendRequest(void);
> unsigned long doRequest=0;
> WiFiClient client;
> AsyncHTTPRequest request;
> void setup() {
>   // put your setup code here, to run once:
>     ConnectToWifi();
>     request.onReadyStateChange(requestCB );
>      
> }
> 
> void loop(){
>  if (millis()>doRequest + 10000)
>     {
>       sendRequest();
>       doRequest = millis();
>     };
> 
> void sendRequest(){
>   
>   if(request.readyState() == reqStates::readyStateUnsent || request.readyState() == reqStates::readyStateDone){
>      
>         if (request.open("GET", "http://192.168.1.183/api/v/1/status"))
>         {
>           
>         if (request.send()==false)
>           {
>             request.abort();
>             Serial.println("failed to send");
>           }
>           else
>            Serial.println("send request");
>         }
>         else
>         {
>           Serial.println("failed to open");
>           request.abort();
>         };
>        
>     }
>     else
>   {
>     Serial.print("not correct readystate in Status:");
>     Serial.println(request.readyState());
>     request.abort();
>     
>   }
> void requestCB(void* optParm, AsyncHTTPRequest* request, int readyState)
> {
> Serial.println(readyState);
>     if(readyState == reqStates::readyStateDone){
>        if (request->responseHTTPcode()==200)
>        {
>          ;
>          Serial.println(request->responseText());
>    }                  
>        else
>        {
>          Serial.print("httpcode:");
>          Serial.println(request->responseHTTPcode());
>         
>        }
>     }
> }
> ```

your void loop() is not closed with } just the if.

after this repair if you still have this problem, try rise the waiting time.
