### ISSUE TITLE
make sure that all data is send before AsyncClient::close()

### ISSUE THREAD

**Issue by tius2000** [me-no-dev/AsyncTCP#137]
Sorry, if this a stupid question. How can I make sure, that all pending data is sent before the connection is actually closed? It seems to me, that `AsyncClient::close(bool now)` closes the connection immediately, regardless of the `now` argument .

Thanks very much for helping!

**Comment by mrengineer7777** [comment]
Not a stupid question. Possible bug.  "now" variable is never used.

**Comment by bertmelis** [comment]
the only way to know is to wait untill all data is acked and only then close.
