### ISSUE TITLE
Correct use of ESP.reset() when using Async Libs?

### ISSUE THREAD

**Issue by gjt211** [me-no-dev/AsyncTCP#16]
Thanks for such a fantastic library. I have a question and have not been able to find an answer.

As far as I can work out, when using any of the Async libraries you should never use the `delay(nn)` function which I understand.

What I am unable to work out is what is the correct way to use the `ESP.reset()` function.
All examples I have found always seem to follow this (note that the delay times vary depending on where you find your example).
```
delay(3000);
ESP.reset();
delay(2000);
```

So with the idea that we can't use the `delay()` function, what is the correct way to do this?

**Comment by me-no-dev** [comment]
usually you set a flag in the async callback and then execute in the loop:
```cpp
static bool rebootRequested = false;

void onData(void* arg, AsyncClient* client, void *data, size_t len){
  char strData[len+1];
  memcpy(strData, data, len);
  strData[len] = 0;
  if(strcmp("reset", strData) == 0){
    rebootRequested = true;
  }
}

void loop(){
  if(rebootRequested){
    ESP.reset();
  }
  //other loop code
}
```
