### ISSUE TITLE
Examples for the AsyncTCP

### ISSUE THREAD

**Issue by martinmmi** [me-no-dev/AsyncTCP#166]
Hello, iam martin from germany and i like to develop a tcp interface for an esp32 application.

How can i start with your AsyncTCP lib 1.2.1 or the new fork for esphome AsyncTCP lib 2.0.0?

I have this tcp sequences from a tcp server:

OFF:
80 30 41 42 43 44 45 46 47 20 20 20 20 20 20 20 20 20

GREEN:
80 31 41 42 43 44 45 46 47 20 20 20 20 20 20 20 20 20

RED:
80 33 41 42 43 44 45 46 47 20 20 20 20 20 20 20 20 20

How can I evaluate this sequences in a tcp client? Are some examples availble? 

Many thanks
Martin

**Comment by IamBuildDifferent** [comment]
Hi, i‘m working on a simalar project. I‘m modifying this code https://github.com/GreenPonik/esp32-asyncTCP-server-example/blob/master/src/main.cpp
Maybe that helps!
