### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by bofh69** [me-no-dev/AsyncTCP#2]
My project's travis build (https://travis-ci.org/bofh69/AiLight/builds/274342483) started to fail today:
```
In file included from .piolibdeps/AsyncTCP_ID1826/src/AsyncTCP.cpp:24:0:
.piolibdeps/AsyncTCP_ID1826/src/AsyncTCP.h:28:29: fatal error: freertos/semphr.h: No such file or directory
#include "freertos/semphr.h"
^
compilation terminated.
```
Shouldn't there be a dependency on the freetos library from this library?

**Comment by me-no-dev** [comment]
is this ESP32?

**Comment by me-no-dev** [comment]
probably PIO issue that we resolved last night :) pull the latest changes and should be fine

**Comment by bofh69** [comment]
Yes, it was with PIO and now it works fine again. :-) Thanks!

**Comment by terryjmyers** [comment]
What's PIO?  I'm having the same issue right now, ESP8266 toolchain.
