### ISSUE TITLE
Can't compile with the latest ESP32 snapshot

### ISSUE THREAD

**Issue by robertgregor** [me-no-dev/AsyncTCP#22]
Hi, seems, that the library can't be anymore compiled with the latest arduino esp32 code:

C:\RH\arduino-1.8.5\hardware\espressif\esp32\libraries\AsyncTCP\src\AsyncTCP.cpp:259:27: error: field 'call' has incomplete type 'tcpip_api_call'

     struct tcpip_api_call call;

                           ^

C:\RH\arduino-1.8.5\hardware\espressif\esp32\libraries\AsyncTCP\src\AsyncTCP.cpp:259:12: note: forward declaration of 'struct tcpip_api_call'

     struct tcpip_api_call call;

**Comment by bertmelis** [comment]
see #19 and #21.

**Comment by robertgregor** [comment]
Hi, OK, thanks, this fixed the issue!
