### ISSUE TITLE
ESP32 simple Webserver hangs network connection completely

### ISSUE THREAD

**Issue by plewka** [me-no-dev/AsyncTCP#33]
I posted a closer description here, but I doubt it's the right place:
https://github.com/espressif/arduino-esp32/issues/2267#issuecomment-455672401

Basic webserver fails immediately when putting synchronous requests to it using
a webside which contains some _small_ pictures. WLAN or LAN makes no difference.
 (Arduino+AsyncWebserver). 

For me it "feels" like an interfacing issue to lwIP or even a problem in lwIP.
Are you able to tell me how to continue debugging?

**Comment by copercini** [comment]
Seems like you are using ethernet of ESP32-EVB, does this problem happen using ESP's wifi connected to the router directly (instead ethernet)?
