### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by faxik** [me-no-dev/AsyncTCP#35]
Hi, as I see, there are no release tags and it is difficult to roll back to a specific release without diving into commit logs.

With the recent update to esp-idf that introduced problems with mesh (non-)working (espressif/esp-idf#2916, espressif/esp-idf#2915),  I wanted to do roll-back but I couldn't figure out which version should I check out.

**Comment by OttoWinter** [comment]
Same here, tagging releases would be really helpful also for release notifications. Right now, I don't see a way to follow the updates of this library without watching the whole repo.

For me this is important as a package author, AsyncTCP's updates have broken builds quite a few times in the past when using pinned arduino-esp32 versions - https://github.com/esphome/issues/issues/476 ; I understand it's hard to test what will be incompatible with what release, but I'd at least like to get notifications when a new release is out.

**Comment by me-no-dev** [comment]
generally this lib is rarely updated. After the update now, I do not expect any that will add/change functionality. And to confess, lib versions here are more or less rushed because of some issue.

**Comment by fah** [comment]
So then this version 1.0 :-)
