### ISSUE TITLE
Slow speed & corruption, am I doing something wrong?

### ISSUE THREAD

**Issue by MiloMindbender** [me-no-dev/AsyncTCP#41]
I have a program that reads 60 bytes of info from an IMU (gyroscope, accelerometer, compass) and sends it out WiFi by TCP.  I'm having trouble getting the throughput I need and I'm wondering if I am doing something wrong or if this is a limit of the hardware?

Minus all the IMU reading stuff, the main loop looks something like
 

void loop() 
{
  int
    loop_start;        // Time in micros at top of loop

  loop_start = micros();
  if(loop_start < next_report)
    return;
  next_report = loop_start + REPORT_TIME;

// Read IMU and put 60 bytes of data into tempbuf

      telemetryClient->write((char*)tempbuf, 60, ASYNC_WRITE_FLAG_COPY | ASYNC_WRITE_FLAG_MORE);

}

Run this at 100hz and it works fine, at 1000hz (still less than 1m bits/sec) and I get all kinds of data corruption.

Do you think I should be able to send data this fast on ESP32?  Anything I can do to make it work?  I have tried using add/send and have the same problems.  Also tried write with the default flags.

The data doesn't have to go out immediately, it can be buffered up till we have a max-size packet (no nagle algorithm needed).

**Comment by JacoGasp** [comment]
Hello @MiloMindbender 
it was a lot of time since your post 😅 but I'm facing the exact same issue. Did you find some workaround? Thanks
