### ISSUE TITLE
LwIP/TCP thread uses 16KB stack

### ISSUE THREAD

**Issue by tve** [me-no-dev/AsyncTCP#47]
The stack size of the LwIP/TCP thread got increased to 16KB, which is quite a memory hog.
Is there a bug that should be fixed to reduce stack size, or perhaps something should be allocated dynamically so it can fail without crashing the whole system?
See https://github.com/me-no-dev/AsyncTCP/blob/master/src/AsyncTCP.cpp#L201
Introduced in commit https://github.com/me-no-dev/AsyncTCP/commit/f1a801fe069eda040d635aa877baf9efe093544c

**Comment by tve** [comment]
Can you comment what drives the size of this stack? Where is what allocated that needs so much space?

**Comment by me-no-dev** [comment]
i did it because we had many memory issues. can go down now again. want to make a PR?

**Comment by danielkucera** [comment]
I'm hitting similar problem with esphome with wifi and BT stack enabled: there seems to be not enough memory to initialize AsyncTCP:
```
[01:35:24][E][AsyncTCP.cpp:1271] begin(): failed to start task
```

**Comment by tve** [comment]
I guess I need to make a PR...

**Comment by pbolduc** [comment]
> The stack size of the LwIP/TCP thread got increased to 16KB, which is quite a memory hog.
> Is there a bug that should be fixed to reduce stack size, or perhaps something should be allocated dynamically so it can fail without crashing the whole system?
> See https://github.com/me-no-dev/AsyncTCP/blob/master/src/AsyncTCP.cpp#L201
> Introduced in commit [f1a801f](https://github.com/me-no-dev/AsyncTCP/commit/f1a801fe069eda040d635aa877baf9efe093544c)

The stack size parameter in creating the task is in words not bytes. So (8192 * 2) words = (8192 * 2 * 4) = 64KB.  [xTaskCreate](https://www.freertos.org/a00125.html) 
> 
<html>
<body>


usStackDepth | The number of words (not bytes!) to allocate for use as the task's stack.
-- | --



</body>
</html>
