### ISSUE TITLE
incompatible with new SDK 2.1

### ISSUE THREAD

**Issue by universam1** [me-no-dev/AsyncTCP#5]
unable to build with latest commits in Arduino for SDK 2.1 - I conclude this is the reason.

Please see the log output here:
https://travis-ci.org/universam1/iSpindel/builds/288929668

**Comment by me-no-dev** [comment]
uhmm this is the ESP32 lib. I fixed the 8266 one last night. Maybe pull the changes?

**Comment by universam1** [comment]
Oh sorry for confusing the repos, and thanks for the quick response!

That sounds great, unfortunately PIO is not updating the repo, did you bump the version?

```
pio lib update
Library Storage: C:\src\Dropbox\Arduino\iSpindel\.piolibdeps
Updating ESPAsyncTCP                     @ 1.1.0          [Up-to-date]
Updating ESPAsyncWebServer               @ 1.1.0          [Up-to-date]
```

**Comment by me-no-dev** [comment]
have not bumped it because I did not have the time to finish everything (SSL) and I did not test it thuraly

**Comment by universam1** [comment]
Since I am using travis with PIO I have no idea how to pull more recent library commits than the releases. If you got an idea, would be glad.

**Comment by universam1** [comment]
closing to move to correct repo
