### ISSUE TITLE
Using hostname on ESP32 fails to connect

### ISSUE THREAD

**Issue by jeroenst** [me-no-dev/AsyncTCP#51]
When using mqttClient.setServer("myserver.lan", 1883) the connection fails on ESP32, on ESP8266 it works fine.

When using mqttClient.setServer(IpAddress(192, 168, 0, 1), 1883) it works fine.

The asyncmqtt library uses client->connect of AsyncTCP which I think fails

**Comment by obrain17** [comment]
This is fixed with pull request #50

**Comment by jeroenst** [comment]
Pull request #50 works, please merge it with master
