### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by Eroc33** [me-no-dev/AsyncTCP#8]
I was under the impression I would be able to use ssl with [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer) on esp32, however as this library doesn't support ssl (whereas it's esp8266 counterpart does) it appears that's not possible?

It would be nice for this lib to be on par with the esp8266 version in terms of features to avoid surprises like this.

Is ssl support a feature that is likely to get implemented?

**Comment by me-no-dev** [comment]
yes it is :) as soon as I have time to investigate Async SSL. Not as easy as normal SSL

**Comment by h3ndrik** [comment]
basecamp is also waiting for someone to implement ssl support:

https://github.com/merlinschumacher/Basecamp/issues/8

**Comment by LaurentLouf** [comment]
Any news on that ?

**Comment by fremouw** [comment]
Hi, I've been working lately on adding TLS support using mbed-tls, I've got it working but the implementation is still a bit rough and needs some cleaning and improvements (and some testing). Anyway, feel free to check it out and make improvements, you can find my fork here: https://github.com/fremouw/AsyncTCP/tree/mbed-tls.

**Comment by mandulaj** [comment]
Bump
Is there any news on this? I am trying to use SSL on my MQTT connection from an ESP32. Since I am using async-mqtt-client, I have managed to trace down the culprit of my failure to here. As far as I can see, the only option is to use Pubsubclient instead right now.

**Comment by LaurentLouf** [comment]
If you can update your esp-idf version, there's an MQTT library included in recent versions. And it supports SSL. From esp-idf 3.3 I think.

**Comment by fremouw** [comment]
> Bump
> Is there any news on this? I am trying to use SSL on my MQTT connection from an ESP32. Since I am using async-mqtt-client, I have managed to trace down the culprit of my failure to here. As far as I can see, the only option is to use Pubsubclient instead right now.

I've created a pull request to add support for TLS, see: https://github.com/me-no-dev/AsyncTCP/pull/43. Works only as a client and I've been using it for MQTTS for some time now.

**Comment by tve** [comment]
Given #48 I believe this can be closed...

**Comment by jeroenst** [comment]
The issue is not resolved (yet) so imo this issue should still be open, right?

**Comment by tve** [comment]
It has been superseded by #48

**Comment by Tanmay-FuelDaddy** [comment]
So It is concluded that this Library is not going to support Async SSL/TLS , but the ESP8266 gets it? 
Perhaps there is a way to port that Lib to 32.
