### ISSUE TITLE
Can't connect on sub directory or other file except index

### ISSUE THREAD

**Issue by alor-pretatma** [me-no-dev/AsyncTCP#85]
`client_tcp->connect("192.168.0.120/another/api/test.php", 80);`
how do i connect in subdirectories like that..?

**Comment by bertmelis** [comment]
You can't. TCP connects to ip addresses and ports.

Alternatives:
- change to other port for your service
- use higher level protocol (tip: [asyncHTTPrequest](https://github.com/boblemaire/asyncHTTPrequest))
- write your own protocol
