### ISSUE TITLE
Guidance to use it with GSM library

### ISSUE THREAD

**Issue by ajinkyaw** [me-no-dev/AsyncTCP#92]
Hi,
I am using TINYGSM library. My primary goal is to execute the apis ( Https Requests ) asynchronously, that means atleast 3 requests must execute in parallel at a time.
please guide me to integrate the AsyncTCP into the TinyGSM. ?

I am using ESP32 and Sim800c in hardware.

**Comment by Wolfleader101** [comment]
Hey, Did you ever get this working?
